ebook_metadata:
  title: ༄༅། །སྨོན་པ་བྱང་ཆུབ་མཆོག་ཏུ་སེམས་བསྐྱེད་པ་ཐེག་ཆེན་ལམ་གྱི་སྙིང་པོའོ། །
  authors:
  - མཛད་པ་པོ། བླ་མ་དམ་པ་བསོོད་ནམས་རྒྱལ་མཚན།
  sku: IBA-SG-01-1
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: Essence of the Mahayana Path:Generating the Aspiration of Sublime Bodhichitta
    bo: སྨོན་པ་བྱང་ཆུབ་མཆོག་ཏུ་སེམས་བསྐྱེད་པ་ཐེག་ཆེན་ལམ་གྱི་སྙིང་པོ།
  collection:
    en: IBA Sonam Gyaltsen Series–  Book 1
    bo: བསོོད་ནམས་རྒྱལ་མཚན་རྩོམ་བྲིས།–  དེབ། ༡
  author:
    en: Lama Dampa Sonam Gyaltsen
    bo: བླ་མ་དམ་པ་བསོོད་ནམས་རྒྱལ་མཚན།
  pusblisher:
    en: IBA Publications
    bo: རྒྱལ་ཡོངས་གསུང་རབ་སློབ་གཉེར་ཁང་།
  sku: IBA-SG-01-1
  category:
    en: Bodhichitta
    bo: བྱང་ཆུབ་ཀྱི་སེམས།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: IBA-SG-01-1.epub
  description:
    en: 'The essence of Mahayana path: generating the sublime Aspirational Bodhicitta
      – Generating Awakening Mind – This text deals with the practice of generating
      the first of the two awakening mind according to the greater vehicle.'
    bo: བླ་མ་དམ་པས་མཛད་པའི་གཞུང་འདི་ནི་དུས་གསུམ་སངས་རྒྱས་ཐམས་ཅད་ཀྱི་གྲོད་པ་གཅིག་པའི་ལམ་གྱི་སྙིང་པོ་ཏེ་ཐེག་ཆེན་སེམས་བསྐྱེད་སྐོར་བཞུགས་ཡོད།
